dist: bionic
language: generic
before_install:
- |
  echo "Checking if a CI run is needed post commit: ${TRAVIS_COMMIT_RANGE}"
  if ! git diff --name-only ${TRAVIS_COMMIT_RANGE} | grep -qvE '(\.png$)|(\.pdf$)|(\.html$)|^(LICENSE)'
  then
    echo "Only doc files were updated, not running the CI."
    exit
  fi
- sudo add-apt-repository --yes ppa:js-reynaud/kicad-5.1
- sudo apt update -y
- sudo apt install --no-install-recommends -y kicad kicad-symbols kicad-templates
  kicad-footprints inkscape
script:
- cd scripts && ./pcb2svg.sh && cd ..
before_deploy:
- git config --local user.name "PCB Gerber Exporter"
- git config --local user.email "noreply@w4xzr.xyz"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
- ls
- ls Gerbers/
deploy:
  provider: releases
  api_key:
    secure: mz8McFer3yr1mEuBGlQ+8EwjQ9smBA9NWsVvyqSGuuRzF7dnj28Zqahxufg1ijkurDjbp7lvN+u02SvXUYif9xGdidKERZH/DQQoQSRmCsxacUKleyI8s5H/KxCCQZq0hka0w1irl1h9uPB1OUOIWE2alH0rNDuFF6mjCRakSH53OstO1tPvontzAowkIW2EfvRTePiLTzyckM7rfpwwdOnQM9PcWBXoYiuMwEi4PXAI19bvHVaW+HQnqiZeFZ3rOy1mGIB8kT/+Q1tFU3V99kZs5eH7eW0kpnaRQar4cFE1kqvVUNws4ev3hb8O3Z9ptXfwhwHsqYIg3s976FC7pF0PcJ7v24Lr5HBu4hQVU1zTIGHK+9CjA0d7U12QCg1ZAfC22chuLfs5sKlqfrWio7REEuqU9I+dbnG4dlP2n24zvZxUobzaEzXMojLrm4IEYi+ANe0dE3t7d+RY1Ys/vc/gzGcsf0HNPgG9luWSVimeuRiiRQz2voL52o885wnmG13AJ1ks+Ogs2Yyo+n8JPcEgMxSZTb1j8dOu7Ap1poyoRcFjqdCX6iUNIhTtt/sJ4RUBkQpL0cH0guFEwKu7EApaagGN3vQWb4u/S7VjNl3a1EmuxPRSHcJR59eImska+wdfqVn8ZfzCZlnmep7l6oDEmFk66iNmS5YKTqRmSK4=
  file: Gerbers/PIN-109_gerbers.zip
  on:
    repo: w4xzr/PIN-109
  skip_cleanup: 'true'
